### ISSUE TITLE
Github action not work

### ISSUE THREAD

**Issue by fewensa** [plumber-cd/terraform-backend-git#22]
```
name: Publish

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Publish terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup terraform-backend-git
        uses: plumber-cd/terraform-backend-git@master
        with:
          version: v0.0.14

      - name: Use command
        run: terraform-backend-git version

```

```
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v2' (SHA:ec3a7ce113134d7a93b817d10a8272cb61118579)
Download action repository 'plumber-cd/terraform-backend-git@master' (SHA:4c80752b81548e985278381231777f7bfecf2638)
Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/_actions/plumber-cd/terraform-backend-git/master'. Did you forget to run actions/checkout before running your local action?
```
