### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by benkeil** [plumber-cd/terraform-backend-git#35]
```yaml
- run: RUNNER_TRACKING_ID="" && (nohup terraform-backend-git --access-logs &)
- run: curl -s 'http://localhost:6061/?type=git&repository=git@github.com:otto-ec/search-di-tf-state.git&ref=main&state=repository-setup'
- uses: hashicorp/terraform-cdk-action@main
  env:
    VAULT_ADDR: ${{ steps.environment_check.outputs.value }}
    GITHUB_MVN_REGISTRY_USERNAME: ${{ env.FKT_USER }}
    GITHUB_MVN_REGISTRY_TOKEN: ${{ env.FKT_GH_TOKEN_WRITE }}
  with:
    workingDirectory: infrastructure/${{ inputs.STACK_NAME }}
    terraformVersion: 1.3.7
    cdktfVersion: 0.15.4
    stackName: ${{ inputs.STACK_NAME }}
    mode: auto-approve-apply
    gitHubToken: ${{ env.FKT_GH_TOKEN_WRITE }}
    commentOnPr: "false"
```

`curl` returns `500 - Internal Server Error`, but it works on my machine. How do I need to configure it so that cdktf can deploy?
